# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Build & Upload package

on:
  release:
    types: [created]

jobs:
  ci-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.12"
    steps:
      - uses: actions/checkout@v4
                    
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.13"
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Lint with ruff
        run: |
          uv run ruff check
      
      - name: Test with pytest
        run: |
          uv run pytest

      
  publish-pypi:
    name: "Publish to PyPI"
    needs:
      - "ci-check"
    runs-on: ubuntu-latest
    environment: "publish-pypi"
    permissions:
      id-token: write # required for trusted publishing
    steps:
      - uses: actions/checkout@v4
                    
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.13"

      - name: Install the project
        run: |
          uv sync --all-extras

      - name: Publish the project to PyPI
        run: |
          uv publish
        # NOTE: This works because of trusted publishing
